### ISSUE TITLE
Public release

### ISSUE THREAD

**Issue by Wenzel** [Wenzel/checksec.py#22]
# TODO

- [x] publish on Pypi
- [x] JSON export
- [x] hide errors
- [ ] documentation
- [x] ci badge
- [x] pypi package badge
- [x] python version badge

**Comment by rtcms** [comment]
For CI we can look into https://docs.travis-ci.com/user/status-images/ 
Also it's free for Open Source - https://travis-ci.com/plans
